---
- name: Setup Nginx with Docker on EC2
  hosts: webservers
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker and dependencies
      apt:
        name:
          - docker-ce
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Restart Docker to ensure it's running
      service:
        name: docker
        state: restarted

    # - name: Add user to docker group
    #   user:
    #     name: ubuntu
    #     groups: docker
    #     append: yes

    # - name: Install Python and pip
    #   apt:
    #     name: python3-pip
    #     state: present

    # - name: Install compatible Docker SDK and Docker Compose
    #   pip:
    #     name:
    #       - docker==6.1.3
    #       - docker-compose==1.29.2
    #     state: present

    # - name: Download Docker Compose binary
    #   get_url:
    #     url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    #     dest: /usr/local/bin/docker-compose
    #     mode: '0755'

    # - name: Create directory for compose file
    #   file:
    #     path: /home/ubuntu/nginx
    #     state: directory
    #     owner: ubuntu
    #     group: ubuntu
    #     mode: '0755'

    - name: Copy docker-compose archive
      copy:
        src: ./docker_compose.tar.gz
        dest: /home/ubuntu/docker_compose.tar.gz
        mode: '0644'

    - name: Extract docker-compose project on instance
      unarchive:
        src: /home/ubuntu/docker_compose.tar.gz
        dest: /home/ubuntu/
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Run Docker Compose project
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/docker_compose
