apiVersion: v1
kind: Service
metadata:
  name: danit-randomstring-service
spec:
  type: NodePort
  selector:
    app: danit-randomstring
  ports:
    - port: 3000          
      targetPort: 8082    
      nodePort: 30007     
