global:
  resolve_timeout: 1m

route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'telegram'
    webhook_configs:
      - url: 'https://api.telegram.org/bot8189301864:AAFPqSVYLkHzbQdAYcJZBFXeWWYQ0X86zlE/sendMessage'
        send_resolved: true
        http_config:
          headers:
            Content-Type: application/json
        message: '{{ template "telegram.default" . }}'

templates:
  - '/etc/alertmanager/templates/telegram.tmpl'
