global:
  resolve_timeout: 1m

route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '<YOUR_BOT_TOKEN>'
        chat_id: '<YOUR_CHAT_ID>'
        message: '{{ template "telegram.default" . }}'

templates:
  - '/etc/alertmanager/template.tmpl'
