version: '3.9'

services:
  monitoring-app:
    build:
      context: ./Monitoring-2
      dockerfile: Dockerfile
    container_name: monitoring-app
    ports:
      - "10000:10000"
    networks:
      efk-net:
        aliases:
          - fluentd-host
    depends_on:
      - fluentd
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: hw26-fluentd-1
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk-net
    depends_on:
      - elasticsearch
    restart: on-failure
    command: /bin/sh -c "sleep 10 && fluentd -c /fluentd/etc/fluent.conf"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: hw26-elasticsearch-1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - efk-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: hw26-kibana-1
    ports:
      - "5601:5601"
    networks:
      - efk-net
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  efk-net:
