apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    app: nginxxx
  annotations:
    description: "Nginx pod with health checks and volume mytest v5"
spec:
  containers:
  - name: nginx
    image: nginx:1.23.3
    ports:
      - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
  volumes:
  - name: nginx-logs
    emptyDir: {}
